# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

stages:
  - build
  - test
  - deploy 

image: gcc

# Build and test after a commit 
build_TNT:
  stage: build
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
  script: 
     - | 
       mkdir build && cd build
       cmake ..
       cmake --build .
  
test_TNT:
  stage: test
  script: 
     - echo ls

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

