# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

stages:
  - build
  - test
  - deploy 

image: gcc


# Build and test after a commit 
build:
  stage: build
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - apt-get install --yes python3-pip
    - apt-get install --yes doxygen
    - pip3 install -U sphinx
    - pip3 install -U sphinx_rtd_theme
    - pip3 install -U breathe
    - pip3 install -U exhale
  script: 
    - | 
      mkdir build && cd build
      cmake ..
      cmake --build .
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - build/
      - Bin/
  
test:
  stage: test
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - build/
      - Bin/
  script:
    - ls 
    - cd build
    - ctest .

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public

